### ISSUE TITLE
flickering tests: `Invalid argument (ip.cpp:136)`

### ISSUE THREAD

**Issue by briandunn** [briandunn/flatware#17]
To reproduce, just run the tests a few times.

Only thing I've been able to narrow down so far:

* it only happens when flatware is trying to clean up
* only happens with multiple workers
* running it with `lldb` has revealed an underlying errno of `No such file or directory`

**Comment by ukeller** [comment]
Hi
Is this an assertion on Zeromq ip.cpp? Which version? 4? Which platform? Osx?
-Urs

**Comment by briandunn** [comment]
This issue seems resolved on master. As best I can tell it was related to a race condition where sometimes we would push to a closed pull, but I was never able to get a simple failing test together.
