### ISSUE TITLE
RSpec command not found.

### ISSUE THREAD

**Issue by andychong1996** [briandunn/flatware#39]
I run the command: `flatware rspec` on the terminal.
Response I got:
The flatware gem is a dependency of flatware runners for rspec and cucumber.  Try adding flatware-rspec or flatware-cucumber to your Gemfile.
Could not find command "rspec".

But I can run it with `flatware fan rspec`. But I think it is running rspec each time on each worker, instead of splitting the tests to 8 parts.

**Comment by WaKeMaTTa** [comment]
I suppose you have `gem 'flatware-rspec', require: false` in your `Gemfile`.

If you use `rbenv` execute this command in the terminal `rbenv rehash`

**Comment by briandunn** [comment]
Like @WaKeMaTTa said, you'll need to make sure you

1. have `flatware-rspec` in your gem file
2. run flatware with those gems available in `loaded_specs`. (https://github.com/briandunn/flatware/blob/master/lib/flatware/cli.rb#L58)

I'm pretty sure there is a better way to detect which runners you have installed, but until I get to that,  if you're not using a ruby version manager, try `bundle exec flatware rspec`.
