### ISSUE TITLE
Process.setpgrp fails in circleci

### ISSUE THREAD

**Issue by ryanong** [briandunn/flatware#66]
`/home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/flatware-2.0.0/lib/flatware/cli.rb:58:in 'setpgrp': Operation not permitted (Errno::EPERM)`

Is this absolutely necessary for this to work?

**Comment by briandunn** [comment]
No it's not, just a housekeeping feature to help me keep track of the relationships between the processes. a `rescue nil` should be fine, maybe with a debug log message.

**Comment by briandunn** [comment]
Of course I've always thought of flatware as a tool for running tests efficiently on my development machine - I think circle has their own recommended ways of parallelizing an rspec suite? If you can get flatware working for that too though - that would be pretty cool.

**Comment by ryanong** [comment]
They parallelize across containers not within a container. I found that parallelizing feature tests where there is a LOT of io sped up tests around 20%
