### ISSUE TITLE
When is Ruby 3.3 expected to be released?

### ISSUE THREAD

**Issue by afuno** [briandunn/flatware#77]
Hello. I saw that support for Ruby 3.3 has been [implemented](https://github.com/briandunn/flatware/pull/76), but is still not released.

Please tell me when you plan to do this?

**Comment by briandunn** [comment]
I can push a release... a little hesitant because I'm not using 3.3 on a daily basis so I haven't really kicked the tires. Have you used flatware on your 3.3 project successfully (via a Gemfile `git` declaration)?

**Comment by briandunn** [comment]
went for it.
